import { createHash } from "node:crypto";

import { eq } from "drizzle-orm";

import { documentVersions } from "@/db/schema";
import type { FoundationDb } from "@/db/types";
import type { DrizzleTx } from "@/db/transaction-context";
import {
  COMMUNITY_STANDARDS_BODY,
  COMMUNITY_STANDARDS_DOCUMENT_ID,
  COMMUNITY_STANDARDS_NOTICE_ID,
  COMMUNITY_STANDARDS_TITLE,
  COMMUNITY_STANDARDS_VERSION_LABEL,
} from "@/lib/auth/community-standards";

/**
 * Deterministic, non-participant operational assent document catalog.
 *
 * Regenerated by alpha reset so a wiped alpha can bootstrap/onboard again
 * without synthetic fixture reseeding. Bodies are provisional alpha-test
 * placeholders — not counsel-approved legal language and not production terms.
 */

export type OperationalAssentDocumentDef = {
  id: string;
  kind: "privacy_notice" | "conduct";
  versionLabel: string;
  title: string;
  body: string;
  requiredNotices: string[];
};

export const OPERATIONAL_PRIVACY_DOCUMENT_ID = "doc-ostt-ops-privacy-v1";

export const OPERATIONAL_ASSENT_DOCUMENTS: readonly OperationalAssentDocumentDef[] =
  [
    {
      id: OPERATIONAL_PRIVACY_DOCUMENT_ID,
      kind: "privacy_notice",
      versionLabel: "v1-ops-alpha",
      title: "Provisional alpha privacy notice (not counsel-approved)",
      body: [
        "Provisional privacy notice for the invite-only gated alpha-test environment.",
        "This text is an engineering placeholder so assent/onboarding can run after an operator reset.",
        "It is not counsel-approved legal language, not a production privacy policy, and not a lasting post-alpha settlement.",
        "Alpha-test interim council clearance (ADR 0007) still governs real-account activation scopes;",
        "participant assent records and presentations remain wipeable alpha data.",
      ].join(" "),
      requiredNotices: ["provisional-alpha-notice"],
    },
    {
      id: COMMUNITY_STANDARDS_DOCUMENT_ID,
      kind: "conduct",
      versionLabel: COMMUNITY_STANDARDS_VERSION_LABEL,
      title: COMMUNITY_STANDARDS_TITLE,
      body: COMMUNITY_STANDARDS_BODY,
      requiredNotices: [COMMUNITY_STANDARDS_NOTICE_ID],
    },
  ] as const;

export function hashOperationalDocumentBody(body: string): string {
  return createHash("sha256").update(body).digest("hex");
}

type DocDb = FoundationDb | DrizzleTx;

/**
 * Clear document_versions and republish the operational catalog.
 * Caller must already have deleted assent_records / presentations / outcomes
 * (FK restrict) and hold the alpha-reset protection window.
 */
export async function regenerateOperationalAssentDocuments(
  db: DocDb,
): Promise<void> {
  await db.delete(documentVersions);

  const reviewedAt = new Date("2026-01-01T00:00:00.000Z");
  const publishedAt = new Date("2026-01-01T00:01:00.000Z");

  for (const def of OPERATIONAL_ASSENT_DOCUMENTS) {
    const contentHash = hashOperationalDocumentBody(def.body);
    await db.insert(documentVersions).values({
      id: def.id,
      kind: def.kind,
      versionLabel: def.versionLabel,
      contentHash,
      title: def.title,
      body: def.body,
      state: "draft",
      requiredNotices: [...def.requiredNotices],
    });
    await db
      .update(documentVersions)
      .set({
        state: "counsel_reviewed",
        counselReviewedAt: reviewedAt,
        counselReviewedByAccountId: null,
        updatedAt: reviewedAt,
      })
      .where(eq(documentVersions.id, def.id));
    await db
      .update(documentVersions)
      .set({
        state: "published",
        publishedAt,
        publishedByAccountId: null,
        updatedAt: publishedAt,
      })
      .where(eq(documentVersions.id, def.id));
  }
}
